version: '3'
services:
  web:
    build: .
    ports: 
    - "8090:8080"
    - "3020:3020"
    - "9229:9229"
    environment:
    - VIRTUAL_HOST=up.danleahu.com
    - VIRTUAL_PORT=8080
    network_mode: bridge
  tusd:
    image: tusproject/tusd
    volumes:
    - ./upload:/srv/tusd-data/data
    ports:
    - "1080:1080"
    network_mode: bridge

